include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}-nginx ${CI_PROJECT_NAME}_${CI_PROJECT_NAME}-caddy
  environment:
    url: https://${DD_TRAEFIK_SUBDOMAIN}.${DD_TRAEFIK_DOMAIN}
