version: '3.7'

services:
  backup-reader:
    image: ${IMAGE_NAME:-nginx}:${IMAGE_TAG:-alpine}
    networks:
      traefik-net:
    volumes:
      - data-vol:/backup:ro
      - htpasswd-vol:/htpasswd
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.http.routers.backup-reader-root.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.backup-reader-root.tls.certresolver: ${TRAEFIK_CERTRESOLVER}
        traefik.http.routers.backup-reader-root.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) && Path(`/`)
        traefik.http.middlewares.backup-reader-root-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.backup-reader-root.middlewares: backup-reader-root-auth
        traefik.http.routers.backup-reader-root.service: backup-reader

        traefik.http.routers.backup-reader-default.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.backup-reader-default.tls.certresolver: ${TRAEFIK_CERTRESOLVER}
        traefik.http.routers.backup-reader-default.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.routers.backup-reader-default.service: backup-reader

        traefik.http.services.backup-reader.loadbalancer.server.port: ${PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

configs:
  nginx-config:
    name: ${NGINX_CONFIG_NAME:-backup-nginx}
    file: ./nginx.conf

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-backup-data-vol}
    driver: local
    driver_opts:
      type: ${DATA_VOL_TYPE}
      o: ${DATA_VOL_OPTIONS}
      device: ${DATA_VOL_DEVICE}

  htpasswd-vol:
    name: ${HTPASSWD_VOL_NAME:-backup-htpasswd-vol}
    driver: local
    driver_opts:
      type: ${HTPASSWD_VOL_TYPE}
      o: ${HTPASSWD_VOL_OPTIONS}
      device: ${HTPASSWD_VOL_DEVICE}
