version: '3.9'

services:
  backup-reader:
    image: ${IMAGE_NAME:-caddy}:${IMAGE_TAG:-latest}
    environment:
      CADDY_PORT:
      BACKUP_DATA_PATH:
    networks:
      traefik-net:
    volumes:
      - data-vol:${BACKUP_DATA_PATH}:ro
    configs:
      - source: caddyfile-config
        target: /etc/caddy/Caddyfile
    healthcheck:
      test: wget --spider -q http://localhost:${CADDY_PORT}/health
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-30s}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'

        traefik.http.routers.backup-reader-root.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.backup-reader-root.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) && Path(`/`)
        traefik.http.middlewares.backup-reader-root-auth.basicauth.users: ${TRAEFIK_ROOT_AUTH}
        traefik.http.routers.backup-reader-root.middlewares: backup-reader-root-auth

        traefik.http.routers.backup-reader-path.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.backup-reader-path.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) && PathPrefix(`/{name:[^/]+}/`)
        traefik.http.middlewares.backup-reader-path-auth.basicauth.users: ${TRAEFIK_PATH_AUTH}
        traefik.http.routers.backup-reader-path.middlewares: backup-reader-path-auth

        traefik.http.services.backup-reader.loadbalancer.server.port: ${CADDY_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-backup-reader-caddyfile}
    file: ./config/Caddyfile

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-backup-data-vol}
    driver: local
    driver_opts:
      type: ${DATA_VOL_TYPE}
      o: addr=${DATA_VOL_ADDR},${DATA_VOL_OPTS}
      device: ${DATA_VOL_DEVICE}
