version: '3.9'

services:
  backup-reader:
    image: ${IMAGE_NAME:-caddy}:${IMAGE_TAG:-latest}
    environment:
      CADDY_PORT:
      BACKUP_DATA_PATH:
      ROOT_USER:
      ROOT_PASS:
      HASHED_PASS_platanito:
      HASHED_PASS_frambuesita:
      HASHED_PASS_tamarillito:
      HASHED_PASS_pitayita:
      HASHED_PASS_pedro:
      HASHED_PASS_pedro-work:
    networks:
      traefik-net:
    volumes:
      - data-vol:${BACKUP_DATA_PATH}:ro
    configs:
      - source: caddyfile-config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.backup-reader.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.backup-reader.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.backup-reader.loadbalancer.server.port: ${CADDY_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-backup-reader-caddyfile}
    file: ./config/Caddyfile

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-backup-data-vol}
    driver: local
    driver_opts:
      type: ${DATA_VOL_TYPE}
      o: addr=${DATA_VOL_ADDR},${VOL_OPTS}
      device: ${DATA_VOL_DEVICE}
